##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.8.0-B50] date: [Thu Feb 19 12:16:49 CET 2026]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = stm32n6_make_template_FSBL

# ST
stlink =  /opt/st/stm32cubeide_2.0.0/plugins/com.st.stm32cube.ide.mcu.externaltools.stlink-gdb-server.linux64_2.2.300.202509021040/tools/bin/ST-LINK_gdbserver
st_prog_bin = /home/kilic/apps/STM32CubeProgrammer/bin
st_prog = $(st_prog_bin)/STM32_Programmer_CLI

# AI
# Processed on NPU or CM55
PROC ?= NPU
MODEL_DIR = onnx_models
MODEL = network
# MODEL = fff_v1
SCRIPT_DIR = scripts
SCRIPT = n6_loader.py 
MODEL_OUTPUT_DIR = st_ai_output
VAL_DIR = AI/Projects/STM32N6570-DK/Applications/$(PROC)_Validation
PROJECT_PATH = /home/kilic/workspace/embedded/stm/stm32n6/make_template_ai/AI/Projects/STM32N6570-DK/Applications/NPU_Validation
SCRIPT_ARGS = --config $(SCRIPT_DIR)/config.json --build-config N6-Nucleo --network-file $(MODEL_OUTPUT_DIR)/$(MODEL).c --project-path $(VAL_DIR)
AI_FLAGS = --st-neural-art
ifeq ($(PROC), CM55)
SCRIPT = cm55_loader.py
SCRIPT_ARGS += 
AI_FLAGS = --c-api legacy
endif





######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32n6xx_it.c \
Core/Src/stm32n6xx_hal_msp.c \
Drivers/BSP/STM32N6xx_Nucleo/stm32n6xx_nucleo.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cortex.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc_ex.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_gpio.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma_ex.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr_ex.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_exti.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_usart.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_usart_ex.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart_ex.c \
Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart.c \
Core/Src/system_stm32n6xx_fsbl.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c  

# ASM sources
ASM_SOURCES =  \
startup_stm32n657xx_fsbl.s

# ASMM sources
ASMM_SOURCES = 



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
GDB = $(GCC_PATH)/$(PREFIX)gdb
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
GDB = $(PREFIX)gdb
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m55

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32N657xx \
-DUSE_NUCLEO_64


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32N6xx_HAL_Driver/Inc \
-IDrivers/CMSIS/Device/ST/STM32N6xx/Include \
-IDrivers/STM32N6xx_HAL_Driver/Inc/Legacy \
-IDrivers/BSP/STM32N6xx_Nucleo \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -mcmse -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32N657XX_AXISRAM2_fsbl.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -Wl,--cmse-implib -Wl,--out-implib=./build/secure_nsclib.o

# default action: build all
all: $(MODEL_OUTPUT_DIR) run_script
# all: $(MODEL_OUTPUT_DIR) run_script convert reset flash gdb_server debug
# all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		


$(MODEL_OUTPUT_DIR):
	stedgeai generate -m $(MODEL_DIR)/$(MODEL)_uint8.onnx --target stm32n6 $(AI_FLAGS) --name $(MODEL)

run_script: 
	python3 $(SCRIPT_DIR)/$(SCRIPT) $(SCRIPT_ARGS)

# Converting meomry files to .hex / not sure why xd
convert:
	$(CP) --change-addresses 0x71000000 -Ibinary -Oihex $(MODEL)_atonbuf.xSPI2.raw $(MODEL)_atonbuf.xSPI2.hex

reset:
	$(st_prog) -q -c port=SWD mode=powerdown freq=2000 ap=1

flash:
	$(st_prog) -q -c port=SWD mode=hotplug ap=1 --extload $(st_prog_bin)/ExternalLoader/MX25UM51245G_STM32N6570-NUCLEO.stldr --download st_ai_output/$(MODEL)_atonbuf.xSPI2.hex --verify

gdb_server:
	$(stlink) -d --frequency 2000 --apid 1 -v --port-number 61234 -cp $(st_prog_bin)

debug:
	$(GDB) -batch --command=AI/Projects/STM32N6570-DK/Applications/NPU_Validation/armgcc/n6_commands.gdb AI/Projects/STM32N6570-DK/Applications/NPU_Validation/armgcc/build/N6-Nucleo/Project.elf



#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR) $(MODEL_OUTPUT_DIR) st_ai_ws *log
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
