from __future__ import annotations
from pathlib import Path
from typing import Mapping, Tuple
import re

from n6_utils_pkg.mpool import MPool

class CFile():
    """
    C-file object
    with utilities to retrieve info from it
    """
    compiler_version:str
    mpools: MPool

    def __init__(self, filename:str):
        self.filename = filename
        self.file = Path(filename)
        self.data = self.file.read_text()
        self.extract_mpools()
        self.extract_mpool_filename()

    def extract_mpools(self):
        """Extract memory pools infos
        This is currently deprecated as not all useful information from the memory pool file is present
        in the C-file (esp: prefix used for memory dumps generated by teh compiler)
        """
        header = self.data[:self.data.find("scheduling epoch=0")]   # all data up to first epoch scheduling...
        self.mpools = MPool.from_string(header)
        
    def get_mpools(self) -> MPool:
        return self.mpools
    
    def get_mpool_offset(self, mpool_name:str) -> str:
        # Returns a string with an hexadecimal offset eg. 0xDEAFBEEF
        #  A key error will be raised if an issue occurs.
        return self.mpools[mpool_name]["offset"]
            
    def extract_mpool_filename(self):
        """
        Extracts mpool file name from C file
        mpool is used to get the prefix of the name of the memdump files
        """
        mpool_filename = "default"
        m = re.search(r"^ \* --load-mpool-file = \"(?P<MPOOL>[^\"]+)\"", self.data, flags=re.MULTILINE)
        if m:
            mpool_filename = m.group("MPOOL")
            if ".mpool" in mpool_filename:
                # old releases of aton compiler
                mpool_filename = mpool_filename[:-len(".mpool")]
        self.mpools.set_filename(mpool_filename)
    
    def get_cname(self):
        return self.file.stem
    
    def get_mtime(self):
        return self.file.stat().st_mtime

    def get_all_offsets(self) -> Mapping[str, str]:
        return self.mpools.get_all_offsets()
    
    @property
    def compiler_version(self) -> Tuple[str,str]:
        m = re.search(r"^ \* GIT_DESCRIPTION \"atonn-v(\d+\.\d+\.\d+)-([0-9a-fA-F]+)-", self.data, flags=re.MULTILINE)
        if m:
            return m.groups()
        else:
            # Error, but return something coherent...
            return ("0.0.0", "0000")
