/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RawData, RawData, 4)


PB_BIND(RawDataAck, RawDataAck, AUTO)


PB_BIND(EncryptionParams, EncryptionParams, AUTO)


PB_BIND(GeneralAcknowledge, GeneralAcknowledge, AUTO)


PB_BIND(MyMessage, MyMessage, 4)





