/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RawData_Status {
    RawData_Status_STATUS_FIRST_CHUNK = 0,
    RawData_Status_STATUS_LAST_CHUNK = 1,
    RawData_Status_STATUS_UNIQUE_CHUNK = 2,
    RawData_Status_STATUS_MIDDLE_CHUNK = 3
} RawData_Status;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(4096) RawData_data_t;
/* Used to send / receive raw data in chunks (or not) */
typedef struct _RawData {
    RawData_Status stat;
    int32_t chunk_no;
    RawData_data_t data; /* COMMENT ME FOR PYTHON (only the [ ... ] part) */
    int32_t base_address;
} RawData;

typedef struct _RawDataAck {
    int32_t chunk_no;
} RawDataAck;

/* Used to send keys and number of rounds from the server to the client */
typedef struct _EncryptionParams {
    pb_callback_t keys;
    int32_t nb_rounds;
} EncryptionParams;

/* general ack */
typedef struct _GeneralAcknowledge {
    char dummy_field;
} GeneralAcknowledge;

typedef struct _MyMessage {
    uint32_t status; /* Provision */
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union _MyMessage_payload {
        EncryptionParams encryption_params;
        RawData raw_data;
        RawDataAck raw_data_ack;
        GeneralAcknowledge ack;
    } payload;
} MyMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RawData_Status_MIN RawData_Status_STATUS_FIRST_CHUNK
#define _RawData_Status_MAX RawData_Status_STATUS_MIDDLE_CHUNK
#define _RawData_Status_ARRAYSIZE ((RawData_Status)(RawData_Status_STATUS_MIDDLE_CHUNK+1))

#define RawData_stat_ENUMTYPE RawData_Status






/* Initializer values for message structs */
#define RawData_init_default                     {_RawData_Status_MIN, 0, {0, {0}}, 0}
#define RawDataAck_init_default                  {0}
#define EncryptionParams_init_default            {{{NULL}, NULL}, 0}
#define GeneralAcknowledge_init_default          {0}
#define MyMessage_init_default                   {0, {{NULL}, NULL}, 0, {EncryptionParams_init_default}}
#define RawData_init_zero                        {_RawData_Status_MIN, 0, {0, {0}}, 0}
#define RawDataAck_init_zero                     {0}
#define EncryptionParams_init_zero               {{{NULL}, NULL}, 0}
#define GeneralAcknowledge_init_zero             {0}
#define MyMessage_init_zero                      {0, {{NULL}, NULL}, 0, {EncryptionParams_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define RawData_stat_tag                         1
#define RawData_chunk_no_tag                     2
#define RawData_data_tag                         3
#define RawData_base_address_tag                 4
#define RawDataAck_chunk_no_tag                  1
#define EncryptionParams_keys_tag                1
#define EncryptionParams_nb_rounds_tag           2
#define MyMessage_status_tag                     1
#define MyMessage_encryption_params_tag          4
#define MyMessage_raw_data_tag                   5
#define MyMessage_raw_data_ack_tag               6
#define MyMessage_ack_tag                        7

/* Struct field encoding specification for nanopb */
#define RawData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    stat,              1) \
X(a, STATIC,   SINGULAR, INT32,    chunk_no,          2) \
X(a, STATIC,   SINGULAR, BYTES,    data,              3) \
X(a, STATIC,   SINGULAR, INT32,    base_address,      4)
#define RawData_CALLBACK NULL
#define RawData_DEFAULT NULL

#define RawDataAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    chunk_no,          1)
#define RawDataAck_CALLBACK NULL
#define RawDataAck_DEFAULT NULL

#define EncryptionParams_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, INT32,    keys,              1) \
X(a, STATIC,   SINGULAR, INT32,    nb_rounds,         2)
#define EncryptionParams_CALLBACK pb_default_field_callback
#define EncryptionParams_DEFAULT NULL

#define GeneralAcknowledge_FIELDLIST(X, a) \

#define GeneralAcknowledge_CALLBACK NULL
#define GeneralAcknowledge_DEFAULT NULL

#define MyMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   status,            1) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,encryption_params,payload.encryption_params),   4) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,raw_data,payload.raw_data),   5) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,raw_data_ack,payload.raw_data_ack),   6) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,ack,payload.ack),   7)
#define MyMessage_CALLBACK NULL
#define MyMessage_DEFAULT NULL
#define MyMessage_payload_encryption_params_MSGTYPE EncryptionParams
#define MyMessage_payload_raw_data_MSGTYPE RawData
#define MyMessage_payload_raw_data_ack_MSGTYPE RawDataAck
#define MyMessage_payload_ack_MSGTYPE GeneralAcknowledge

extern const pb_msgdesc_t RawData_msg;
extern const pb_msgdesc_t RawDataAck_msg;
extern const pb_msgdesc_t EncryptionParams_msg;
extern const pb_msgdesc_t GeneralAcknowledge_msg;
extern const pb_msgdesc_t MyMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RawData_fields &RawData_msg
#define RawDataAck_fields &RawDataAck_msg
#define EncryptionParams_fields &EncryptionParams_msg
#define GeneralAcknowledge_fields &GeneralAcknowledge_msg
#define MyMessage_fields &MyMessage_msg

/* Maximum encoded size of messages (where known) */
/* EncryptionParams_size depends on runtime parameters */
/* MyMessage_size depends on runtime parameters */
#define GeneralAcknowledge_size                  0
#define MESSAGE_PB_H_MAX_SIZE                    RawData_size
#define RawDataAck_size                          11
#define RawData_size                             4123

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
