# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# COMMENTED OUT TO PREVENT RUNTIME VERSION CHECK (and "ensure" compatibility with pb3.20.3)
#from google.protobuf import runtime_version as _runtime_version
#_runtime_version.ValidateProtobufRuntimeVersion(
#    _runtime_version.Domain.PUBLIC,
#    5,
#    29,
#    0,
#    '',
#    'message.proto'
#)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\xc9\x01\n\x07RawData\x12\x1d\n\x04stat\x18\x01 \x01(\x0e\x32\x0f.RawData.Status\x12\x10\n\x08\x63hunk_no\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x14\n\x0c\x62\x61se_address\x18\x04 \x01(\x05\"i\n\x06Status\x12\x16\n\x12STATUS_FIRST_CHUNK\x10\x00\x12\x15\n\x11STATUS_LAST_CHUNK\x10\x01\x12\x17\n\x13STATUS_UNIQUE_CHUNK\x10\x02\x12\x17\n\x13STATUS_MIDDLE_CHUNK\x10\x03\"\x1e\n\nRawDataAck\x12\x10\n\x08\x63hunk_no\x18\x01 \x01(\x05\"3\n\x10\x45ncryptionParams\x12\x0c\n\x04keys\x18\x01 \x03(\x05\x12\x11\n\tnb_rounds\x18\x02 \x01(\x05\"\x14\n\x12GeneralAcknowledge\"\xbd\x01\n\tMyMessage\x12\x0e\n\x06status\x18\x01 \x01(\r\x12.\n\x11\x65ncryption_params\x18\x04 \x01(\x0b\x32\x11.EncryptionParamsH\x00\x12\x1c\n\x08raw_data\x18\x05 \x01(\x0b\x32\x08.RawDataH\x00\x12#\n\x0craw_data_ack\x18\x06 \x01(\x0b\x32\x0b.RawDataAckH\x00\x12\"\n\x03\x61\x63k\x18\x07 \x01(\x0b\x32\x13.GeneralAcknowledgeH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAWDATA']._serialized_start=18
  _globals['_RAWDATA']._serialized_end=219
  _globals['_RAWDATA_STATUS']._serialized_start=114
  _globals['_RAWDATA_STATUS']._serialized_end=219
  _globals['_RAWDATAACK']._serialized_start=221
  _globals['_RAWDATAACK']._serialized_end=251
  _globals['_ENCRYPTIONPARAMS']._serialized_start=253
  _globals['_ENCRYPTIONPARAMS']._serialized_end=304
  _globals['_GENERALACKNOWLEDGE']._serialized_start=306
  _globals['_GENERALACKNOWLEDGE']._serialized_end=326
  _globals['_MYMESSAGE']._serialized_start=329
  _globals['_MYMESSAGE']._serialized_end=518
# @@protoc_insertion_point(module_scope)
