/* Called each time just after the reset command is issued: Restore part of the ram that may have been erased because of a reset. */
execUserReset() {
	__message "*** RESET: Re-load image partially erased by IAR reset\n";
	/* Disable RISAF2 */
    __writeMemory32(0, 0x54028040, "Memory");
    __writeMemory32(0, 0x54028080, "Memory");
    __writeMemory32(0, 0x540280C0, "Memory");
    __writeMemory32(0, 0x54028100, "Memory");
    __writeMemory32(0, 0x54028140, "Memory");
    __writeMemory32(0, 0x54028180, "Memory");
    __writeMemory32(0, 0x540281C0, "Memory");

    /* Disable SAU */
    __writeMemory32(0, 0xe000edd0, "Memory");

    /* Disable MPU */
    __writeMemory32(0, 0xe000ed24, "Memory");
	
    /* Reload image partially erased by IAR reset */
    __loadImage("$EXE_DIR$\\$TARGET_FNAME$", 0, 0);

    __restoreSoftwareBreakpoints();
}


__REMOVE__ME__IF__ITCM__execUserPreload()
{
  /* Extend TCM */
  __writeMemory32(0x00000088, 0x56008008, "Memory"); /* HAL_SYSCFG_SetTCMSize SYSCFG_DTCM_128K, SYSCFG_ITCM_128K */
  __writeMemory32(0x00000001, 0x56008018, "Memory"); /* HAL_SYSCFG_EnablePowerOnReset */
  
  __hwReset(2);	// Reset the CPU an halts it 2ms afterwards
  
  /* Init TCM ECC */
  __fillMemory32(0, 0x10000000, "Memory", 32768, "Copy"); /* 128 KB */
  __fillMemory32(0, 0x30000000, "Memory", 32768, "Copy"); /* 128 KB */
}