
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_network.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_DEFAULT_H
#define __STAI_ATON_DEFAULT_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_DEFAULT_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_DEFAULT_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_network_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_network_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_network_get_context_size(void)
{
  return STAI_DEFAULT_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_network_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_network_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_network_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_network_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_network_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_network_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_network_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_network_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_network_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_network_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_network_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_network_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_DEFAULT_STATES_NUM  (0)
#define STAI_DEFAULT_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_DEFAULT_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_DEFAULT_IN_NUM (1)
#define STAI_DEFAULT_IN_ALIGNMENTS \
  { \
    16 \
  }
#define STAI_DEFAULT_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_DEFAULT_IN_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_DEFAULT_IN_SIZES \
  { \
    784 \
  }
#define STAI_DEFAULT_IN_SIZES_BYTES \
  { \
    784 \
  }

#define STAI_DEFAULT_IN_1_ALIGNMENT (16)
#define STAI_DEFAULT_IN_1_NAME "Input_0_out_0"
#define STAI_DEFAULT_IN_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_DEFAULT_IN_1_FORMAT (STAI_FORMAT_S8)
#define STAI_DEFAULT_IN_1_SIZE (784)
#define STAI_DEFAULT_IN_1_SIZE_BYTES (784)
#define STAI_DEFAULT_IN_1_CHANNEL (28)
#define STAI_DEFAULT_IN_1_HEIGHT (28)
#define STAI_DEFAULT_IN_1_WIDTH (1)
#define STAI_DEFAULT_IN_1_BATCH (1)
#define STAI_DEFAULT_IN_1_RANK (4)
#define STAI_DEFAULT_IN_1_SHAPE \
  { \
    1, 28, 28, 1 \
  }
#define STAI_DEFAULT_IN_1_SCALE_OFFSET_NUM (1)
#define STAI_DEFAULT_IN_1_SCALES \
  { \
    0.00392156885936856 \
  }
#define STAI_DEFAULT_IN_1_OFFSETS \
  { \
    -128 \
  }

/********************************** OUTPUTS **********************************/
#define STAI_DEFAULT_OUT_NUM (1)
#define STAI_DEFAULT_OUT_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_DEFAULT_OUT_NAMES \
  { \
    "Quantize_14_out_0" \
  }
#define STAI_DEFAULT_OUT_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_DEFAULT_OUT_SIZES \
  { \
    10 \
  }
#define STAI_DEFAULT_OUT_SIZES_BYTES \
  { \
    10 \
  }

#define STAI_DEFAULT_OUT_1_ALIGNMENT (32)
#define STAI_DEFAULT_OUT_1_NAME "Quantize_14_out_0"
#define STAI_DEFAULT_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE)
#define STAI_DEFAULT_OUT_1_FORMAT (STAI_FORMAT_S8)
#define STAI_DEFAULT_OUT_1_SIZE (10)
#define STAI_DEFAULT_OUT_1_SIZE_BYTES (10)
#define STAI_DEFAULT_OUT_1_CHANNEL (1)
#define STAI_DEFAULT_OUT_1_HEIGHT (1)
#define STAI_DEFAULT_OUT_1_WIDTH (10)
#define STAI_DEFAULT_OUT_1_RANK (2)
#define STAI_DEFAULT_OUT_1_SHAPE \
  { \
    1, 10 \
  }
#define STAI_DEFAULT_OUT_1_SCALE_OFFSET_NUM (1)
#define STAI_DEFAULT_OUT_1_SCALES \
  { \
    0.00390625 \
  }
#define STAI_DEFAULT_OUT_1_OFFSETS \
  { \
    -128 \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_DEFAULT_WEIGHTS_NUM (11)
#define STAI_DEFAULT_WEIGHTS_ALIGNMENTS \
  { \
    32, 32, 16, 16, 32, 32, 16, 16, 16, 32, 32 \
  }
#define STAI_DEFAULT_WEIGHTS_NAMES \
  { \
    "Conv2D_3_weights", "Gemm_10_weights_transposed_3", "Conv2D_3_zero_off_8", "Conv2D_3_off_bias_14", "Gemm_10_conv_4_zero_off_17", "Gemm_10_conv_4_off_bias_23", "Conv2D_3_off_bias_12_A_16_50", "Gemm_10_squeeze_y_5_51_atonn_internal_scale", "Gemm_10_squeeze_y_5_51_atonn_internal_offset", "Softmax_13_53_atonn_internal_scale", "Softmax_13_53_atonn_internal_offset" \
  }
#define STAI_DEFAULT_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_S8, STAI_FORMAT_S32, STAI_FORMAT_Q15, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7, STAI_FORMAT_FLOAT32, STAI_FORMAT_Q7 \
  }
#define STAI_DEFAULT_WEIGHTS_SIZES \
  { \
    108, 20280, 1, 12, 1, 10, 12, 1, 1, 1, 1 \
  }
#define STAI_DEFAULT_WEIGHTS_SIZES_BYTES \
  { \
    108, 20280, 1, 48, 1, 40, 24, 4, 1, 4, 1 \
  }

#define STAI_DEFAULT_WEIGHTS_1_ALIGNMENT (32)
#define STAI_DEFAULT_WEIGHTS_1_NAME "Conv2D_3_weights"
#define STAI_DEFAULT_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_DEFAULT_WEIGHTS_1_FORMAT (STAI_FORMAT_S8)
#define STAI_DEFAULT_WEIGHTS_1_SIZE (108)
#define STAI_DEFAULT_WEIGHTS_1_SIZE_BYTES (108)
#define STAI_DEFAULT_WEIGHTS_1_CHANNEL (1)
#define STAI_DEFAULT_WEIGHTS_1_HEIGHT (3)
#define STAI_DEFAULT_WEIGHTS_1_WIDTH (3)
#define STAI_DEFAULT_WEIGHTS_1_BATCH (1)
#define STAI_DEFAULT_WEIGHTS_1_RANK (4)
#define STAI_DEFAULT_WEIGHTS_1_SHAPE \
  { \
    12, 3, 3, 1 \
  }
#define STAI_DEFAULT_WEIGHTS_1_SCALE_OFFSET_NUM (12)
#define STAI_DEFAULT_WEIGHTS_1_SCALES \
  { \
    0.00607369653880596, 0.00847823917865753, 0.00744093488901854, 0.00977082829922438, 0.00916179455816746, 0.00443987548351288, 0.0128004290163517, 0.00972248986363411, 0.0061003458686173, 0.0036040844861418, 0.0126981623470783, 0.0069799367338419 \
  }
#define STAI_DEFAULT_WEIGHTS_1_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_DEFAULT_WEIGHTS_2_ALIGNMENT (32)
#define STAI_DEFAULT_WEIGHTS_2_NAME "Gemm_10_weights_transposed_3"
#define STAI_DEFAULT_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_DEFAULT_WEIGHTS_2_FORMAT (STAI_FORMAT_S8)
#define STAI_DEFAULT_WEIGHTS_2_SIZE (20280)
#define STAI_DEFAULT_WEIGHTS_2_SIZE_BYTES (20280)
#define STAI_DEFAULT_WEIGHTS_2_CHANNEL (2028)
#define STAI_DEFAULT_WEIGHTS_2_HEIGHT (1)
#define STAI_DEFAULT_WEIGHTS_2_WIDTH (1)
#define STAI_DEFAULT_WEIGHTS_2_BATCH (78)
#define STAI_DEFAULT_WEIGHTS_2_RANK (5)
#define STAI_DEFAULT_WEIGHTS_2_SHAPE \
  { \
    10, 26, 1, 1, 78 \
  }
#define STAI_DEFAULT_WEIGHTS_2_SCALE_OFFSET_NUM (1)
#define STAI_DEFAULT_WEIGHTS_2_SCALES \
  { \
    0.0107212830334902 \
  }
#define STAI_DEFAULT_WEIGHTS_2_OFFSETS \
  { \
    0 \
  }

#define STAI_DEFAULT_WEIGHTS_3_ALIGNMENT (16)
#define STAI_DEFAULT_WEIGHTS_3_NAME "Conv2D_3_zero_off_8"
#define STAI_DEFAULT_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_DEFAULT_WEIGHTS_3_FORMAT (STAI_FORMAT_S8)
#define STAI_DEFAULT_WEIGHTS_3_SIZE (1)
#define STAI_DEFAULT_WEIGHTS_3_SIZE_BYTES (1)
#define STAI_DEFAULT_WEIGHTS_3_CHANNEL (1)
#define STAI_DEFAULT_WEIGHTS_3_HEIGHT (1)
#define STAI_DEFAULT_WEIGHTS_3_WIDTH (1)
#define STAI_DEFAULT_WEIGHTS_3_RANK (1)
#define STAI_DEFAULT_WEIGHTS_3_SHAPE \
  { \
    1 \
  }
#define STAI_DEFAULT_WEIGHTS_3_SCALE_OFFSET_NUM (1)
#define STAI_DEFAULT_WEIGHTS_3_SCALES \
  { \
    0.00392156885936856 \
  }
#define STAI_DEFAULT_WEIGHTS_3_OFFSETS \
  { \
    0 \
  }

#define STAI_DEFAULT_WEIGHTS_4_ALIGNMENT (16)
#define STAI_DEFAULT_WEIGHTS_4_NAME "Conv2D_3_off_bias_14"
#define STAI_DEFAULT_WEIGHTS_4_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_HAS_BATCH)
#define STAI_DEFAULT_WEIGHTS_4_FORMAT (STAI_FORMAT_S32)
#define STAI_DEFAULT_WEIGHTS_4_SIZE (12)
#define STAI_DEFAULT_WEIGHTS_4_SIZE_BYTES (48)
#define STAI_DEFAULT_WEIGHTS_4_CHANNEL (12)
#define STAI_DEFAULT_WEIGHTS_4_HEIGHT (1)
#define STAI_DEFAULT_WEIGHTS_4_WIDTH (1)
#define STAI_DEFAULT_WEIGHTS_4_BATCH (6)
#define STAI_DEFAULT_WEIGHTS_4_RANK (4)
#define STAI_DEFAULT_WEIGHTS_4_SHAPE \
  { \
    2, 1, 1, 6 \
  }
#define STAI_DEFAULT_WEIGHTS_4_SCALE_OFFSET_NUM (0)
#define STAI_DEFAULT_WEIGHTS_4_SCALES \
  { \
  }
#define STAI_DEFAULT_WEIGHTS_4_OFFSETS \
  { \
  }

#define STAI_DEFAULT_WEIGHTS_5_ALIGNMENT (32)
#define STAI_DEFAULT_WEIGHTS_5_NAME "Gemm_10_conv_4_zero_off_17"
#define STAI_DEFAULT_WEIGHTS_5_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_DEFAULT_WEIGHTS_5_FORMAT (STAI_FORMAT_S8)
#define STAI_DEFAULT_WEIGHTS_5_SIZE (1)
#define STAI_DEFAULT_WEIGHTS_5_SIZE_BYTES (1)
#define STAI_DEFAULT_WEIGHTS_5_CHANNEL (1)
#define STAI_DEFAULT_WEIGHTS_5_HEIGHT (1)
#define STAI_DEFAULT_WEIGHTS_5_WIDTH (1)
#define STAI_DEFAULT_WEIGHTS_5_RANK (1)
#define STAI_DEFAULT_WEIGHTS_5_SHAPE \
  { \
    1 \
  }
#define STAI_DEFAULT_WEIGHTS_5_SCALE_OFFSET_NUM (1)
#define STAI_DEFAULT_WEIGHTS_5_SCALES \
  { \
    0.0108646713197231 \
  }
#define STAI_DEFAULT_WEIGHTS_5_OFFSETS \
  { \
    0 \
  }

#define STAI_DEFAULT_WEIGHTS_6_ALIGNMENT (32)
#define STAI_DEFAULT_WEIGHTS_6_NAME "Gemm_10_conv_4_off_bias_23"
#define STAI_DEFAULT_WEIGHTS_6_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_DEFAULT_WEIGHTS_6_FORMAT (STAI_FORMAT_S32)
#define STAI_DEFAULT_WEIGHTS_6_SIZE (10)
#define STAI_DEFAULT_WEIGHTS_6_SIZE_BYTES (40)
#define STAI_DEFAULT_WEIGHTS_6_CHANNEL (10)
#define STAI_DEFAULT_WEIGHTS_6_HEIGHT (1)
#define STAI_DEFAULT_WEIGHTS_6_WIDTH (1)
#define STAI_DEFAULT_WEIGHTS_6_BATCH (10)
#define STAI_DEFAULT_WEIGHTS_6_RANK (3)
#define STAI_DEFAULT_WEIGHTS_6_SHAPE \
  { \
    1, 1, 10 \
  }
#define STAI_DEFAULT_WEIGHTS_6_SCALE_OFFSET_NUM (0)
#define STAI_DEFAULT_WEIGHTS_6_SCALES \
  { \
  }
#define STAI_DEFAULT_WEIGHTS_6_OFFSETS \
  { \
  }

#define STAI_DEFAULT_WEIGHTS_7_ALIGNMENT (16)
#define STAI_DEFAULT_WEIGHTS_7_NAME "Conv2D_3_off_bias_12_A_16_50"
#define STAI_DEFAULT_WEIGHTS_7_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_DEFAULT_WEIGHTS_7_FORMAT (STAI_FORMAT_Q15)
#define STAI_DEFAULT_WEIGHTS_7_SIZE (12)
#define STAI_DEFAULT_WEIGHTS_7_SIZE_BYTES (24)
#define STAI_DEFAULT_WEIGHTS_7_CHANNEL (12)
#define STAI_DEFAULT_WEIGHTS_7_HEIGHT (1)
#define STAI_DEFAULT_WEIGHTS_7_WIDTH (1)
#define STAI_DEFAULT_WEIGHTS_7_BATCH (12)
#define STAI_DEFAULT_WEIGHTS_7_RANK (3)
#define STAI_DEFAULT_WEIGHTS_7_SHAPE \
  { \
    1, 1, 12 \
  }
#define STAI_DEFAULT_WEIGHTS_7_SCALE_OFFSET_NUM (0)
#define STAI_DEFAULT_WEIGHTS_7_SCALES \
  { \
  }
#define STAI_DEFAULT_WEIGHTS_7_OFFSETS \
  { \
  }

#define STAI_DEFAULT_WEIGHTS_8_ALIGNMENT (16)
#define STAI_DEFAULT_WEIGHTS_8_NAME "Gemm_10_squeeze_y_5_51_atonn_internal_scale"
#define STAI_DEFAULT_WEIGHTS_8_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_DEFAULT_WEIGHTS_8_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_DEFAULT_WEIGHTS_8_SIZE (1)
#define STAI_DEFAULT_WEIGHTS_8_SIZE_BYTES (4)
#define STAI_DEFAULT_WEIGHTS_8_CHANNEL (1)
#define STAI_DEFAULT_WEIGHTS_8_HEIGHT (1)
#define STAI_DEFAULT_WEIGHTS_8_WIDTH (1)
#define STAI_DEFAULT_WEIGHTS_8_RANK (1)
#define STAI_DEFAULT_WEIGHTS_8_SHAPE \
  { \
    1 \
  }
#define STAI_DEFAULT_WEIGHTS_8_SCALE_OFFSET_NUM (0)
#define STAI_DEFAULT_WEIGHTS_8_SCALES \
  { \
  }
#define STAI_DEFAULT_WEIGHTS_8_OFFSETS \
  { \
  }

#define STAI_DEFAULT_WEIGHTS_9_ALIGNMENT (16)
#define STAI_DEFAULT_WEIGHTS_9_NAME "Gemm_10_squeeze_y_5_51_atonn_internal_offset"
#define STAI_DEFAULT_WEIGHTS_9_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_DEFAULT_WEIGHTS_9_FORMAT (STAI_FORMAT_Q7)
#define STAI_DEFAULT_WEIGHTS_9_SIZE (1)
#define STAI_DEFAULT_WEIGHTS_9_SIZE_BYTES (1)
#define STAI_DEFAULT_WEIGHTS_9_CHANNEL (1)
#define STAI_DEFAULT_WEIGHTS_9_HEIGHT (1)
#define STAI_DEFAULT_WEIGHTS_9_WIDTH (1)
#define STAI_DEFAULT_WEIGHTS_9_RANK (1)
#define STAI_DEFAULT_WEIGHTS_9_SHAPE \
  { \
    1 \
  }
#define STAI_DEFAULT_WEIGHTS_9_SCALE_OFFSET_NUM (0)
#define STAI_DEFAULT_WEIGHTS_9_SCALES \
  { \
  }
#define STAI_DEFAULT_WEIGHTS_9_OFFSETS \
  { \
  }

#define STAI_DEFAULT_WEIGHTS_10_ALIGNMENT (32)
#define STAI_DEFAULT_WEIGHTS_10_NAME "Softmax_13_53_atonn_internal_scale"
#define STAI_DEFAULT_WEIGHTS_10_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_DEFAULT_WEIGHTS_10_FORMAT (STAI_FORMAT_FLOAT32)
#define STAI_DEFAULT_WEIGHTS_10_SIZE (1)
#define STAI_DEFAULT_WEIGHTS_10_SIZE_BYTES (4)
#define STAI_DEFAULT_WEIGHTS_10_CHANNEL (1)
#define STAI_DEFAULT_WEIGHTS_10_HEIGHT (1)
#define STAI_DEFAULT_WEIGHTS_10_WIDTH (1)
#define STAI_DEFAULT_WEIGHTS_10_RANK (1)
#define STAI_DEFAULT_WEIGHTS_10_SHAPE \
  { \
    1 \
  }
#define STAI_DEFAULT_WEIGHTS_10_SCALE_OFFSET_NUM (0)
#define STAI_DEFAULT_WEIGHTS_10_SCALES \
  { \
  }
#define STAI_DEFAULT_WEIGHTS_10_OFFSETS \
  { \
  }

#define STAI_DEFAULT_WEIGHTS_11_ALIGNMENT (32)
#define STAI_DEFAULT_WEIGHTS_11_NAME "Softmax_13_53_atonn_internal_offset"
#define STAI_DEFAULT_WEIGHTS_11_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_DEFAULT_WEIGHTS_11_FORMAT (STAI_FORMAT_Q7)
#define STAI_DEFAULT_WEIGHTS_11_SIZE (1)
#define STAI_DEFAULT_WEIGHTS_11_SIZE_BYTES (1)
#define STAI_DEFAULT_WEIGHTS_11_CHANNEL (1)
#define STAI_DEFAULT_WEIGHTS_11_HEIGHT (1)
#define STAI_DEFAULT_WEIGHTS_11_WIDTH (1)
#define STAI_DEFAULT_WEIGHTS_11_RANK (1)
#define STAI_DEFAULT_WEIGHTS_11_SHAPE \
  { \
    1 \
  }
#define STAI_DEFAULT_WEIGHTS_11_SCALE_OFFSET_NUM (0)
#define STAI_DEFAULT_WEIGHTS_11_SCALES \
  { \
  }
#define STAI_DEFAULT_WEIGHTS_11_OFFSETS \
  { \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_DEFAULT_WEIGHTS_NUM (0)
#define STAI_DEFAULT_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_DEFAULT_WEIGHTS_NAMES \
  { \
  }
#define STAI_DEFAULT_WEIGHTS_FORMATS \
  { \
  }
#define STAI_DEFAULT_WEIGHTS_SIZES \
  { \
  }
#define STAI_DEFAULT_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_DEFAULT_ACTIVATIONS_NUM (0)
#define STAI_DEFAULT_ACTIVATIONS_ALIGNMENTS \
  { \
  }
#define STAI_DEFAULT_ACTIVATIONS_NAMES \
  { \
  }
#define STAI_DEFAULT_ACTIVATIONS_FORMATS \
  { \
  }
#define STAI_DEFAULT_ACTIVATIONS_SIZES \
  { \
  }
#define STAI_DEFAULT_ACTIVATIONS_SIZES_BYTES \
  { \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_DEFAULT_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_DEFAULT_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_DEFAULT_ORIGIN_MODEL_NAME "mnist_int8_io_i8_OE_3_3_1"
#define STAI_DEFAULT_C_MODEL_NAME "Default"

/*************************** RELATIVE MEMORY POOLS ***************************/
/* no memory pools with relative addresses */

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_DEFAULT_H
